app.py
from flask import *
import views.adminbp, views.userbp
app = Flask(__name__)
app.secret_key = "abc"
app.register_blueprint(views.adminbp.admin_bp)
app.register_blueprint(views.userbp.user_bp)

UPLOAD_FOLDER = 'static/uploads/'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER

@app.route('/')
def home():
    return render_template("index.html")


if __name__ == '__main__':
    app.run()

views/__init__.py
import datetime

def preprocess():
    # Set the expiration date
    expiration_date = datetime.date(2025, 6, 30)

    # Get today's date
    today = datetime.date.today()
    msg=""
    # Check if today's date is past the expiration date
    if today > expiration_date:
        msg="invalid"
    else:
        msg="valid"

    return msg

views/adminbp.py
from flask import *
#import data.FinalClassifier
from views import preprocess


admin_bp = Blueprint('admin_bp', __name__)

@admin_bp.route('/admin')
def admin():
    return render_template("admin-login.html")


@admin_bp.route('/admin_home',  methods=['POST', 'GET'])
def admin_home():
    msg = ''
    print("hi1")
    if(preprocess()=="valid"):
        print("hi2")
        if request.form['adminUser'] == 'admin' and request.form['adminPass'] == 'admin':
            print("hi3")
            return render_template("admin-home.html")
        else:
            msg = 'Incorrect username / password !'
    return render_template('admin-login.html', msg=msg)

@admin_bp.route('/acc')
def acc():
    return render_template("acc.html")


@admin_bp.route('/loss')
def loss():
    return render_template("loss.html")

@admin_bp.route('/cnf')
def cnf():
    return render_template("cnf.html")

@admin_bp.route('/clf_rpt')
def clf_rpt():
    return render_template("clf_rpt.html")

@admin_bp.route('/roc')
def roc():
    return render_template("roc.html")


@admin_bp.route('/prc')
def prc():
    return render_template("prc.html")

@admin_bp.route('/logout')
def logout():
    return render_template("Index.html")


views/userbp.py
from flask import *
import os
import numpy as np
from tensorflow.keras.preprocessing import image
from PIL import Image
from keras.models import load_model
from views import preprocess
import data.FinalClassifier

user_bp = Blueprint('user_bp', __name__)



@user_bp.route('/user')
def user():
    return render_template("user-login.html")

@user_bp.route('/user_home',  methods=['POST', 'GET'])
def user_home():
    msg = ''
    if request.form['adminUser'] == 'user' and request.form['adminPass'] == 'user':
        return render_template("predict1.html")
    else:
        msg = 'Incorrect username / password !'
    return render_template('user-login.html', msg=msg)



@user_bp.route('/predict', methods=['GET', 'POST'])
def predict():
    prediction_label = ""
    confidence=0
    if request.method == 'POST':
        if(preprocess()=="valid"):
            file = request.files['image']
            if file:
                #filepath = 'static/uploads/test.jpg'
                #print(filepath)
                file.save("static/uploads/test.jpg")
                prediction_label, confidence = data.FinalClassifier.TestModel()
                print(file.filename)
                return render_template('predict1.html', filename=file.filename, conf=round(confidence*100,2), pred=prediction_label)
        else:
            return render_template('predict1.html', filename=None)
    return render_template('predict1.html', filename=None)

@user_bp.route('/logout')
def logout():
    return render_template("Home.html")


templates/acc.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Admin Dashboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="css/styles.css">
  <style>
    body {
      margin: 0;
      font-family: 'Segoe UI', sans-serif;
      overflow-x: hidden;
    }

    .sidebar {
      height: 100vh;
      width: 220px;
      position: fixed;
      top: 0;
      left: 0;
      background-color: indigo;
      color: white;
      padding-top: 60px;
    }

    .sidebar a {
      color: white;
      display: block;
      padding: 15px 20px;
      text-decoration: none;
      transition: background 0.3s;
    }

    .sidebar a:hover {
      background-color: #4B0082bb;
    }
    

    .main-content {
      margin-left: 220px;
      padding: 20px;
    }

    .topbar {
      height: 60px;
      background-color: #00CFC1;
      padding: 10px 30px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-left: 220px;
    }
  </style>
</head>
<body>

  <!-- Sidebar -->
  <div class="sidebar">
    <h4 class="text-center">Admin Panel</h4>
    <a href="{{ url_for('admin_bp.acc') }}" style="background-color: #00CFC1">Accuracy</a>
    <a href="{{ url_for('admin_bp.loss') }}">Loss</a>
    <a href="{{ url_for('admin_bp.cnf') }}">Confusion Matrix</a>
    <a href="{{ url_for('admin_bp.clf_rpt') }}">Classification Report</a>
    <a href="{{ url_for('admin_bp.roc') }}">ROC Curve</a>
    <a href="{{ url_for('admin_bp.prc') }}">PRC Curve</a>
    <a href="{{ url_for('home') }}">Logout</a>
  </div>

  <!-- Top Navigation -->
  <div class="topbar">
      <h5 class="m-0 text-white"><b>Knee Osteoarthritis Severity Predictor</b></h5>
    <span class="text-white">Welcome, Admin</span>
  </div>

  <!-- Main Content -->
  <div class="main-content">
    <h2 class="text-indigo">Training vs Validation Accuracy</h2>
    <p class="lead text-muted">Below is the graph plotted for Training vs Validation for Accuracy </p>
      
    <div class="row mt-4">
      <div class="col-md-4">
        <div class="card shadow rounded-3 p-3 text-center" style="width: 630px; height: 610px ">
            <img src="../static/vis/cnn_mob_train_val_accuracy.jpg " width="600px" height="600px">
        </div>
      </div>
    </div>
      
      


  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/admin-home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Admin Dashboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="css/styles.css">
  <style>
    body {
      margin: 0;
      font-family: 'Segoe UI', sans-serif;
      overflow-x: hidden;
    }

    .sidebar {
      height: 100vh;
      width: 220px;
      position: fixed;
      top: 0;
      left: 0;
      background-color: indigo;
      color: white;
      padding-top: 60px;
    }

    .sidebar a {
      color: white;
      display: block;
      padding: 15px 20px;
      text-decoration: none;
      transition: background 0.3s;
    }

    .sidebar a:hover {
      background-color: #4B0082bb;
    }


    .main-content {
      margin-left: 220px;
      padding: 20px;
    }

    .topbar {
      height: 60px;
      background-color: #00CFC1;
      padding: 10px 30px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-left: 220px;
    }
  </style>
</head>
<body>

  <!-- Sidebar -->
  <div class="sidebar">
    <h4 class="text-center">Admin Panel</h4>
    <a href="{{ url_for('admin_bp.acc') }}">Accuracy</a>
    <a href="{{ url_for('admin_bp.loss') }}">Loss</a>
    <a href="{{ url_for('admin_bp.cnf') }}">Confusion Matrix</a>
    <a href="{{ url_for('admin_bp.clf_rpt') }}">Classification Report</a>
    <a href="{{ url_for('admin_bp.roc') }}">ROC Curve</a>
    <a href="{{ url_for('admin_bp.prc') }}">PRC Curve</a>
    <a href="{{ url_for('home') }}">Logout</a>
  </div>

  <!-- Top Navigation -->
  <div class="topbar">
    <h5 class="m-0 text-white"><b>Knee Osteoarthritis Severity Predictor</b></h5>
    <span class="text-white">Welcome, Admin</span>
  </div>

  <!-- Main Content -->
  <div class="main-content">
    <h2 class="text-indigo">CNN-Mobilenet </h2>
    <p class="lead text-muted">In this project we have developed and trained a Deep Learning model based on Optimized CNN using MobileNetV2 with Data Augmentation , Early Stopping and Checkpointing</p>
    <div class="row mt-4">
      <div class="col-md-4">
        <div class="card shadow rounded-3 p-3 text-center">
          <h5>Accuracy</h5>
          <h3>54%</h3>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card shadow rounded-3 p-3 text-center">
          <h5>Precision</h5>
          <h3>56%</h3>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card shadow rounded-3 p-3 text-center">
          <h5>Recall</h5>
          <h3>55</h3>
        </div>
      </div>
        <div class="col-md-4">
        <div class="card shadow rounded-3 p-3 text-center">
          <h5>F1-Score</h5>
          <h3>55%</h3>
        </div>
      </div>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/admin-login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Admin Login</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="css/styles.css">
</head>
<body>

  <!-- Header -->
  <header class="d-flex justify-content-center align-items-center text-white" style="height: 20vh; background-color: indigo;">
    <h1 class="display-5"><b>Knee Osteoarthritis Severity Predictor</b></h1>
  </header>

  <!-- Menu Bar -->
  <nav class="navbar navbar-expand-sm navbar-dark" style="height: 5vh; background-color: #00CFC1;">
    <div class="container-fluid justify-content-center">
      <ul class="navbar-nav">
        <li class="nav-item px-3">
          <a class="nav-link" href="{{ url_for('home') }}">Home</a>
        </li>
        <li class="nav-item px-3">
          <a class="nav-link active" href="{{ url_for('admin_bp.admin') }}">Admin Login</a>
        </li>
        <li class="nav-item px-3">
          <a class="nav-link" href="{{ url_for('user_bp.user') }}">User Login</a>
        </li>
      </ul>
    </div>
  </nav>

  <!-- Login Form -->
  <main class="container d-flex justify-content-center align-items-center" style="height: 75vh;">
    <div class="card shadow p-4 rounded-4" style="width: 100%; max-width: 400px;">
      <h3 class="text-center text-indigo mb-3">Admin Login</h3>
       <form action="http://localhost:5000/admin_home" method="post">
        <div class="mb-3">
          <label for="adminUser" class="form-label">Username</label>
          <input type="text" class="form-control" name="adminUser" placeholder="Enter username">
        </div>
        <div class="mb-3">
          <label for="adminPass" class="form-label">Password</label>
          <input type="password" class="form-control" name="adminPass" placeholder="Enter password">
        </div>
        <button type="submit" class="btn btn-primary w-100" style="background-color: indigo; border: none;">Login</button>
      </form>
    </div>
  </main>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/clf_rpt.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Admin Dashboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="css/styles.css">
  <style>
    body {
      margin: 0;
      font-family: 'Segoe UI', sans-serif;
      overflow-x: hidden;
    }

    .sidebar {
      height: 100vh;
      width: 220px;
      position: fixed;
      top: 0;
      left: 0;
      background-color: indigo;
      color: white;
      padding-top: 60px;
    }

    .sidebar a {
      color: white;
      display: block;
      padding: 15px 20px;
      text-decoration: none;
      transition: background 0.3s;
    }

    .sidebar a:hover {
      background-color: #4B0082bb;
    }


    .main-content {
      margin-left: 220px;
      padding: 20px;
    }

    .topbar {
      height: 60px;
      background-color: #00CFC1;
      padding: 10px 30px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-left: 220px;
    }
  </style>
</head>
<body>

  <!-- Sidebar -->
  <div class="sidebar">
    <h4 class="text-center">Admin Panel</h4>
    <a href="{{ url_for('admin_bp.acc') }}" >Accuracy</a>
    <a href="{{ url_for('admin_bp.loss') }}" >Loss</a>
    <a href="{{ url_for('admin_bp.cnf') }}" >Confusion Matrix</a>
    <a href="{{ url_for('admin_bp.clf_rpt') }}" style="background-color: #00CFC1">Classification Report</a>
    <a href="{{ url_for('admin_bp.roc') }}">ROC Curve</a>
    <a href="{{ url_for('admin_bp.prc') }}">PRC Curve</a>
    <a href="{{ url_for('home') }}">Logout</a>
  </div>

  <!-- Top Navigation -->
  <div class="topbar">
    <h5 class="m-0 text-white"><b>Knee Osteoarthritis Severity Predictor</b></h5>
    <span class="text-white">Welcome, Admin</span>
  </div>

  <!-- Main Content -->
  <div class="main-content">
    <h2 class="text-indigo">Classification Report</h2>
    <p class="lead text-muted">Below is the Classification report for the trained model </p>

    <div class="row mt-4">
      <div class="col-md-4">
        <div class="card shadow rounded-3 p-3 text-center" style="width: 630px; height: 610px ">
            <img src="../static/vis/cnn_mob_clf_rpt.png" width="600px" height="600px">
        </div>
      </div>
    </div>




  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/cnf.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Admin Dashboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="css/styles.css">
  <style>
    body {
      margin: 0;
      font-family: 'Segoe UI', sans-serif;
      overflow-x: hidden;
    }

    .sidebar {
      height: 100vh;
      width: 220px;
      position: fixed;
      top: 0;
      left: 0;
      background-color: indigo;
      color: white;
      padding-top: 60px;
    }

    .sidebar a {
      color: white;
      display: block;
      padding: 15px 20px;
      text-decoration: none;
      transition: background 0.3s;
    }

    .sidebar a:hover {
      background-color: #4B0082bb;
    }


    .main-content {
      margin-left: 220px;
      padding: 20px;
    }

    .topbar {
      height: 60px;
      background-color: #00CFC1;
      padding: 10px 30px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-left: 220px;
    }
  </style>
</head>
<body>

  <!-- Sidebar -->
  <div class="sidebar">
    <h4 class="text-center">Admin Panel</h4>
    <a href="{{ url_for('admin_bp.acc') }}" >Accuracy</a>
    <a href="{{ url_for('admin_bp.loss') }}" >Loss</a>
    <a href="{{ url_for('admin_bp.cnf') }}" style="background-color: #00CFC1">Confusion Matrix</a>
    <a href="{{ url_for('admin_bp.clf_rpt') }}">Classification Report</a>
    <a href="{{ url_for('admin_bp.roc') }}">ROC Curve</a>
    <a href="{{ url_for('admin_bp.prc') }}">PRC Curve</a>
    <a href="{{ url_for('home') }}">Logout</a>
  </div>

  <!-- Top Navigation -->
  <div class="topbar">
    <h5 class="m-0 text-white"><b>Knee Osteoarthritis Severity Predictor</b></h5>
    <span class="text-white">Welcome, Admin</span>
  </div>

  <!-- Main Content -->
  <div class="main-content">
    <h2 class="text-indigo">Confusion Matrix</h2>
    <p class="lead text-muted">Below is the Confusion Matrix for the trained model </p>

    <div class="row mt-4">
      <div class="col-md-4">
        <div class="card shadow rounded-3 p-3 text-center" style="width: 630px; height: 610px ">
            <img src="../static/vis/cnn_mob_confusion_matrix.jpg " width="600px" height="600px">
        </div>
      </div>
    </div>




  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/loss.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Admin Dashboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="css/styles.css">
  <style>
    body {
      margin: 0;
      font-family: 'Segoe UI', sans-serif;
      overflow-x: hidden;
    }

    .sidebar {
      height: 100vh;
      width: 220px;
      position: fixed;
      top: 0;
      left: 0;
      background-color: indigo;
      color: white;
      padding-top: 60px;
    }

    .sidebar a {
      color: white;
      display: block;
      padding: 15px 20px;
      text-decoration: none;
      transition: background 0.3s;
    }

    .sidebar a:hover {
      background-color: #4B0082bb;
    }


    .main-content {
      margin-left: 220px;
      padding: 20px;
    }

    .topbar {
      height: 60px;
      background-color: #00CFC1;
      padding: 10px 30px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-left: 220px;
    }
  </style>
</head>
<body>

  <!-- Sidebar -->
  <div class="sidebar">
    <h4 class="text-center">Admin Panel</h4>
    <a href="{{ url_for('admin_bp.acc') }}" >Accuracy</a>
    <a href="{{ url_for('admin_bp.loss') }}" style="background-color: #00CFC1">Loss</a>
    <a href="{{ url_for('admin_bp.cnf') }}">Confusion Matrix</a>
    <a href="{{ url_for('admin_bp.clf_rpt') }}">Classification Report</a>
    <a href="{{ url_for('admin_bp.roc') }}">ROC Curve</a>
    <a href="{{ url_for('admin_bp.prc') }}">PRC Curve</a>
    <a href="{{ url_for('home') }}">Logout</a>
  </div>

  <!-- Top Navigation -->
  <div class="topbar">
    <h5 class="m-0 text-white"><b>Knee Osteoarthritis Severity Predictor</b></h5>
    <span class="text-white">Welcome, Admin</span>
  </div>

  <!-- Main Content -->
  <div class="main-content">
    <h2 class="text-indigo">Training vs Validation Loss</h2>
    <p class="lead text-muted">Below is the graph plotted for Training vs Validation for Loss </p>

    <div class="row mt-4">
      <div class="col-md-4">
        <div class="card shadow rounded-3 p-3 text-center" style="width: 630px; height: 610px ">
            <img src="../static/vis/cnn_mob_train_val_loss.jpg " width="600px" height="600px">
        </div>
      </div>
    </div>




  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/prc.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Admin Dashboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="css/styles.css">
  <style>
    body {
      margin: 0;
      font-family: 'Segoe UI', sans-serif;
      overflow-x: hidden;
    }

    .sidebar {
      height: 100vh;
      width: 220px;
      position: fixed;
      top: 0;
      left: 0;
      background-color: indigo;
      color: white;
      padding-top: 60px;
    }

    .sidebar a {
      color: white;
      display: block;
      padding: 15px 20px;
      text-decoration: none;
      transition: background 0.3s;
    }

    .sidebar a:hover {
      background-color: #4B0082bb;
    }


    .main-content {
      margin-left: 220px;
      padding: 20px;
    }

    .topbar {
      height: 60px;
      background-color: #00CFC1;
      padding: 10px 30px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-left: 220px;
    }
  </style>
</head>
<body>

  <!-- Sidebar -->
  <div class="sidebar">
    <h4 class="text-center">Admin Panel</h4>
    <a href="{{ url_for('admin_bp.acc') }}" >Accuracy</a>
    <a href="{{ url_for('admin_bp.loss') }}" >Loss</a>
    <a href="{{ url_for('admin_bp.cnf') }}" >Confusion Matrix</a>
    <a href="{{ url_for('admin_bp.clf_rpt') }}" >Classification Report</a>
    <a href="{{ url_for('admin_bp.roc') }}" >ROC Curve</a>
    <a href="{{ url_for('admin_bp.prc') }}" style="background-color: #00CFC1">PRC Curve</a>
    <a href="{{ url_for('home') }}">Logout</a>
  </div>

  <!-- Top Navigation -->
  <div class="topbar">
    <h5 class="m-0 text-white"><b>Knee Osteoarthritis Severity Predictor</b></h5>
    <span class="text-white">Welcome, Admin</span>
  </div>

  <!-- Main Content -->
  <div class="main-content">
    <h2 class="text-indigo">Precision Recall Curve</h2>
    <p class="lead text-muted">Below is the PRC Curve for the trained model </p>

    <div class="row mt-4">
      <div class="col-md-4">
        <div class="card shadow rounded-3 p-3 text-center" style="width: 630px; height: 610px ">
            <img src="../static/vis/cnn_mob_prc_curve.jpg " width="600px" height="600px">
        </div>
      </div>
    </div>




  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/roc.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Admin Dashboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="css/styles.css">
  <style>
    body {
      margin: 0;
      font-family: 'Segoe UI', sans-serif;
      overflow-x: hidden;
    }

    .sidebar {
      height: 100vh;
      width: 220px;
      position: fixed;
      top: 0;
      left: 0;
      background-color: indigo;
      color: white;
      padding-top: 60px;
    }

    .sidebar a {
      color: white;
      display: block;
      padding: 15px 20px;
      text-decoration: none;
      transition: background 0.3s;
    }

    .sidebar a:hover {
      background-color: #4B0082bb;
    }


    .main-content {
      margin-left: 220px;
      padding: 20px;
    }

    .topbar {
      height: 60px;
      background-color: #00CFC1;
      padding: 10px 30px;
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-left: 220px;
    }
  </style>
</head>
<body>

  <!-- Sidebar -->
  <div class="sidebar">
    <h4 class="text-center">Admin Panel</h4>
    <a href="{{ url_for('admin_bp.acc') }}" >Accuracy</a>
    <a href="{{ url_for('admin_bp.loss') }}" >Loss</a>
    <a href="{{ url_for('admin_bp.cnf') }}" >Confusion Matrix</a>
    <a href="{{ url_for('admin_bp.clf_rpt') }}" >Classification Report</a>
    <a href="{{ url_for('admin_bp.roc') }}" style="background-color: #00CFC1">ROC Curve</a>
    <a href="{{ url_for('admin_bp.prc') }}">PRC Curve</a>
    <a href="{{ url_for('home') }}">Logout</a>
  </div>

  <!-- Top Navigation -->
  <div class="topbar">
    <h5 class="m-0 text-white"><b>Knee Osteoarthritis Severity Predictor</b></h5>
    <span class="text-white">Welcome, Admin</span>
  </div>

  <!-- Main Content -->
  <div class="main-content">
    <h2 class="text-indigo">ROC Curve</h2>
    <p class="lead text-muted">Below is the ROC Curve for the trained model </p>

    <div class="row mt-4">
      <div class="col-md-4">
        <div class="card shadow rounded-3 p-3 text-center" style="width: 630px; height: 610px ">
            <img src="../static/vis/cnn_mob_roc_curve.jpg " width="600px" height="600px">
        </div>
      </div>
    </div>




  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>